# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Kv Tech Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: K v Tech Forum created in Disqus

# Your name, as you want it to appear underneath each post and in the footer
author: Karthikeyan V

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /Jekyll-Disqus-Forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://kvvchetty.github.io/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: kvtechforum

# The public key for your disqus application
disqus_publickey: oo8lA472iDFXq0t4w1XyRdS2jPFKpPoYsZ7UdsaodHVKDbc4OR5wcsUdDX4MlaT3
